services:
  server:
    build: ./Server
    container_name: server
    ports:
      - "1580:4000"
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./Client
    container_name: client
    ports:
      - "5173:3000"
    environment:
      - VITE_API_URL=http://38.137.5.56:1580  # Public API endpoint
    networks:
      - fullstack-net
    depends_on:
      - server
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge
