services:
  server:
    build: ./Server          # Folder name where your server Dockerfile exists
    container_name: server
    ports:
      - "1580:4000"          # Host:Container → 1580 (public) → 4000 (inside container)
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./Client          # Folder name where your client Dockerfile exists
    container_name: client
    ports:
      - "5173:3000"          # Host:Container → 5173 (public) → 3000 (inside container)
    networks:
      - fullstack-net
    depends_on:
      - server
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge
